//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testWCFSimpleClient.SimpleMathService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleMathService.IMathService")]
    public interface IMathService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/Add", ReplyAction="http://tempuri.org/IMathService/AddResponse")]
        int Add(int lhs, int rhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/Add", ReplyAction="http://tempuri.org/IMathService/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int lhs, int rhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/Subtract", ReplyAction="http://tempuri.org/IMathService/SubtractResponse")]
        int Subtract(int lhs, int rhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/Subtract", ReplyAction="http://tempuri.org/IMathService/SubtractResponse")]
        System.Threading.Tasks.Task<int> SubtractAsync(int lhs, int rhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/Multify", ReplyAction="http://tempuri.org/IMathService/MultifyResponse")]
        int Multify(int lhs, int rhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/Multify", ReplyAction="http://tempuri.org/IMathService/MultifyResponse")]
        System.Threading.Tasks.Task<int> MultifyAsync(int lhs, int rhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/Divide", ReplyAction="http://tempuri.org/IMathService/DivideResponse")]
        int Divide(int lhs, int rhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/Divide", ReplyAction="http://tempuri.org/IMathService/DivideResponse")]
        System.Threading.Tasks.Task<int> DivideAsync(int lhs, int rhs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathServiceChannel : testWCFSimpleClient.SimpleMathService.IMathService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathServiceClient : System.ServiceModel.ClientBase<testWCFSimpleClient.SimpleMathService.IMathService>, testWCFSimpleClient.SimpleMathService.IMathService {
        
        public MathServiceClient() {
        }
        
        public MathServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int lhs, int rhs) {
            return base.Channel.Add(lhs, rhs);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int lhs, int rhs) {
            return base.Channel.AddAsync(lhs, rhs);
        }
        
        public int Subtract(int lhs, int rhs) {
            return base.Channel.Subtract(lhs, rhs);
        }
        
        public System.Threading.Tasks.Task<int> SubtractAsync(int lhs, int rhs) {
            return base.Channel.SubtractAsync(lhs, rhs);
        }
        
        public int Multify(int lhs, int rhs) {
            return base.Channel.Multify(lhs, rhs);
        }
        
        public System.Threading.Tasks.Task<int> MultifyAsync(int lhs, int rhs) {
            return base.Channel.MultifyAsync(lhs, rhs);
        }
        
        public int Divide(int lhs, int rhs) {
            return base.Channel.Divide(lhs, rhs);
        }
        
        public System.Threading.Tasks.Task<int> DivideAsync(int lhs, int rhs) {
            return base.Channel.DivideAsync(lhs, rhs);
        }
    }
}
